"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ORDER_HTML = exports.RESET_PASSWORD_HTML = void 0;
var RESET_PASSWORD_HTML = function (link) {
    return "\n      <!DOCTYPE html>\n        <html>\n        <head>\n          <style>\n            .disclaimer {\n              color: #455a64;\n              text-decoration: underline;\n            }\n            .button {\n              display: inline-block;\n              padding: 10px 20px;\n              font-size: 16px;\n              background-color: #fff;\n              color: #455a64;\n              text-decoration: none;\n              border-radius: 26px;\n              border: 1px solid rgba(0, 0, 0, 0.4);\n            }\n          </style>\n        </head>\n        <body>\n          <p>Hola,</p>\n          <p>Has solicitado recuperar tu contrase\u00F1a. Puedes restablecerla haciendo clic en el siguiente enlace:</p>\n          <div><a class=\"button\" href=\"".concat(link, "\">Cambiar mi contrase\u00F1a ahora.</a></div>\n          <p>").concat(link, "</p>\n          <p class=\"disclaimer\">\n            <span>\u00C9ste enlace solo funcionara durante 1h, despu\u00E9s tendr\u00E1s que volver a realizar la petici\u00F3n.</span>\n            No olvides revisar tu correo no deseado (spam) si no encuentras el email\n          </p>.\n        </body>\n        </html>\n        \n      ");
};
exports.RESET_PASSWORD_HTML = RESET_PASSWORD_HTML;
var ORDER_HTML = function (newUser) { return "\n  <body>\n    <ul>\n      <li>Usuario: ".concat(newUser.name, " ").concat(newUser.lastName, "</li>\n      <li>Tel\u00E9fono: ").concat(newUser.phone, "</li>\n      <li>Fecha de solicitud: ").concat(new Date().toLocaleString(), "</li>\n      <li>Direcci\u00F3n: ").concat(newUser.address, "</li>\n      <li>Ciudad: ").concat(newUser.city, "</li>\n      <li>DNI: ").concat(newUser.VATIN, "</li>\n      <li>Usuario con correo electr\u00F3nico ").concat(newUser.email, ", solicita acceso.</li>\n      <strong>Accede a tu panel de administrador desde el siguiente enlance: </strong>\n      <a target=\"_blank\" href=\"").concat(process.env.SERVER_URI, "\" alt=\"Enlace al administrador\">\n        Haz click aqui para acceder.\n      </a>\n    </ul>\n  </body>\n"); };
exports.ORDER_HTML = ORDER_HTML;
